name: Build Game for Windows

on:
  workflow_call:
    inputs:
      game_name:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 🧰 Install NSIS
        run: choco install nsis -y

      - name: 📚 Install Python deps
        shell: bash
        run: |
          pip install --upgrade pip
          pip install pyinstaller pygame pillow

      - name: 🧱 Build EXE
        shell: bash
        env:
          GAME_NAME: ${{ inputs.game_name }}
        run: |
          cd games/$GAME_NAME
          python3 -m venv .venv-windows
          source .venv-windows/Scripts/activate
          pyinstaller --noconfirm --onefile --windowed --add-data "assets;assets" --name $GAME_NAME main.py
